# Form implementation generated from reading ui file 'startGui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_startGui(object):
    def setupUi(self, startGui):
        startGui.setObjectName("startGui")
        startGui.resize(361, 284)
        self.gridLayout = QtWidgets.QGridLayout(startGui)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=startGui)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_Selector = QtWidgets.QComboBox(parent=self.frame_2)
        self.comboBox_Selector.setObjectName("comboBox_Selector")
        self.verticalLayout_2.addWidget(self.comboBox_Selector)
        self.pushButton_Crear = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_Crear.setObjectName("pushButton_Crear")
        self.verticalLayout_2.addWidget(self.pushButton_Crear)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.pushButton_Load = QtWidgets.QPushButton(parent=startGui)
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.gridLayout.addWidget(self.pushButton_Load, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)

        self.retranslateUi(startGui)
        QtCore.QMetaObject.connectSlotsByName(startGui)

    def retranslateUi(self, startGui):
        _translate = QtCore.QCoreApplication.translate
        startGui.setWindowTitle(_translate("startGui", "Dialog"))
        self.label.setText(_translate("startGui", "Redes configuradas"))
        self.pushButton_Crear.setText(_translate("startGui", "Crear.."))
        self.pushButton_Load.setText(_translate("startGui", "Cargar"))
